name: Build - PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build-pr:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-restore --no-build

    - name: Test Coverage SoloX.BlazorLayout.UTests
      id: coverage-utest
      run: |
        dotnet test ./src/tests/SoloX.BlazorLayout.UTests --configuration Release --no-restore --no-build --collect:"XPlat Code Coverage" --settings coverlet.runsettings
        echo "::set-output name=FILE::$(find ./src/tests/SoloX.BlazorLayout.UTests -name 'coverage.info' -print)"
    - name: Moving test results
      run: mv ./src/tests/SoloX.BlazorLayout.UTests/TestResults/**/coverage.cobertura.xml ./src/tests/SoloX.BlazorLayout.UTests/TestResults/coverage.cobertura.xml
    - name: Send to coverals
      uses: coverallsapp/github-action@v2.2.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: ./src/tests/SoloX.BlazorLayout.UTests/TestResults/coverage.cobertura.xml
        format: cobertura
        flag-name: coverage-utest
        parallel: true

    - name: Finish coverals
      uses: coverallsapp/github-action@v2.2.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
